house/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('detail/<int:pk>/', views.detail, name='detail'),
    path('create/', views.create, name='create'),
    path('create/house<int:pk>', views.create_house, name='create_house'),
    path('create/apartment/<int:pk>', views.create_apartment, name='create_apartment'),
]

nedviga/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('house.urls', 'nedviga'), namespace='house')),
    path('auth/', include(('users.urls', 'nedviga'), namespace='auth')),
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.sign_in, name='login'),
    path('profile/', views.profile, name='profile'),
    path('logout/', views.out, name='logout')
]

house/models.py
from django.contrib.auth.models import User
from django.db.models import *

Material_choise = [
    ('дерево', 'дерево'),
    ('кирпич', 'кирпич'),
    ('керамические блоки', 'керамические блоки'),
    ('газобетон', 'газобетон'),
]

Type_choise = [
    ('дом', 'дом'),
    ('квартира', 'квартира'),
    ('земельный участок', 'земельный участок'),

]

Furniture = [
    ('С мебелью', 'С мебелью'),
    ('Без мебели', 'Без мебели'),
    ('Частично', 'Частично'),
    ('Только кухня', 'Только кухня'),
    ('Только санузел', 'Только санузел'),
]

Repair = [
    ('Евро ремонт', 'Евро ремонт'),
    ('Черновая отделка', 'Черновая отделка'),
    ('Без ремонта', 'Без ремонта'),
    ('Частичная отделка', 'Частичная отделка'),
]

Building_type = [
    ('Новостройка', 'Новостройка'),
    ('Панельный дом', 'Панельный дом'),
    ('Кирпичный дом', 'Кирпичный дом'),
]

Location = [
    ('В городе', 'В городе'),
    ('Пригород', 'Пригород'),
    ('За городом', 'За городом'),
]


class House(Model):
    type = CharField(max_length=25, choices=Type_choise)
    title = CharField(max_length=255)
    bio = TextField()
    address = CharField(max_length=255)
    preview = ImageField(null=True, blank=True)
    price = IntegerField()
    size = IntegerField()
    material = CharField(max_length=255, choices=Material_choise)
    rooms = IntegerField()
    furniture = CharField(max_length=20, choices=Furniture)
    repair = CharField(max_length=20, choices=Repair)
    near = TextField(null=True, blank=True)
    date_of_building = IntegerField(max_length=4, null=True, blank=True)
    seller = ForeignKey(User, on_delete=CASCADE, null=True)
    #################
    floor = IntegerField(null=True, blank=True)
    storeys = IntegerField(null=True, blank=True)
    building_type = CharField(max_length=20, choices=Building_type)
    #################
    living_space = IntegerField(null=True)
    location = CharField(max_length=20, choices=Location)
    convenience = TextField(null=True)
    date_added = DateTimeField(null=True, auto_now_add=True)

    def __str__(self):
        return self.title


class Image(Model):
    house = ForeignKey(House, on_delete=CASCADE)
    image = ImageField(blank=True, null=True)

    def __str__(self):
        return self.house.title


class Image(Model):
    house = ForeignKey(House, on_delete=CASCADE, related_name='house')
    image1 = ImageField(blank=True)
    image2 = ImageField(blank=True)
    image3 = ImageField(blank=True)
    image4 = ImageField(blank=True)
    image5 = ImageField(blank=True)
    image6 = ImageField(blank=True)
    image7 = ImageField(null=True)
    image8 = ImageField(null=True)
    image9 = ImageField(null=True)
    image10 = ImageField(null=True)
    image11 = ImageField(null=True)
    image12 = ImageField(null=True)
    image13 = ImageField(null=True)
    image14 = ImageField(null=True)
    image15 = ImageField(null=True)
    image16 = ImageField(null=True)

    def __str__(self):
        return str(self.house)

house/forms.py
import os

from django import forms
from .models import *


class BaseForm(forms.ModelForm):
    type = forms.ChoiceField(choices=Type_choise)
    title = forms.CharField(widget=forms.TextInput(attrs={'class': 'input'}))
    bio = forms.TextInput()
    preview = forms.ImageField()
    address = forms.CharField(widget=forms.TextInput(attrs={'class': 'input'}))
    price = forms.IntegerField(widget=forms.NumberInput(attrs={'class': 'input has-text-centered'}))
    size = forms.IntegerField(widget=forms.NumberInput(attrs={'class': 'input has-text-centered'}))
    material = forms.ChoiceField(choices=Material_choise)
    rooms = forms.IntegerField(widget=forms.NumberInput(attrs={'class': 'input has-text-centered', 'maxlength': '3',
                                                               'oninput': 'javascript: if (this.value.length > this.maxLength) this.value = this.value.slice(0, this.maxLength)'}))
    furniture = forms.ChoiceField(choices=Furniture)
    repair = forms.ChoiceField(choices=Repair)
    near = forms.TextInput()
    date_of_building = forms.IntegerField(
        widget=forms.NumberInput(attrs={'class': 'input has-text-centered', 'maxlength': '4',
                                        'oninput': 'javascript: if (this.value.length > this.maxLength) this.value = this.value.slice(0, this.maxLength)'}))

    class Meta:
        model = House
        fields = [
            'type', 'title', 'bio', 'preview', 'address',
            'price',
            'size', 'material', 'rooms', 'furniture', 'repair',
            'near', 'date_of_building', ]


class ApartamentForm(forms.ModelForm):
    floor = forms.IntegerField(widget=forms.NumberInput(attrs={'class': 'input'}))
    storeys = forms.IntegerField(widget=forms.NumberInput(attrs={'class': 'input'}))
    building_type = forms.ChoiceField(choices=Building_type)

    class Meta:
        model = House
        fields = ['floor', 'storeys', 'building_type']


class HouseForm(forms.ModelForm):
    living_space = forms.IntegerField(widget=forms.NumberInput(attrs={'class': 'input'}))
    location = forms.ChoiceField(choices=Location)
    convenience = forms.TextInput()

    class Meta:
        model = House
        fields = ['living_space', 'location', 'convenience']


class CustomFileField(forms.FileInput):
    template_name = 'file.html'


class ImageForm(forms.ModelForm):
    image1 = forms.ImageField()
    image2 = forms.ImageField()
    image3 = forms.ImageField()
    image4 = forms.ImageField()
    image5 = forms.ImageField()
    image6 = forms.ImageField()
    image7 = forms.ImageField()
    image8 = forms.ImageField()
    image9 = forms.ImageField()
    image10 = forms.ImageField()
    image11 = forms.ImageField()
    image12 = forms.ImageField()
    image13 = forms.ImageField()
    image14 = forms.ImageField()
    image15 = forms.ImageField()
    image16 = forms.ImageField()

    class Meta:
        model = Image
        fields = ['image1', 'image2', 'image3', 'image4', 'image5', 'image6',
                  'image7', 'image8', 'image9', 'image10', 'image11', 'image12', 'image13', 'image14', 'image15',
                  'image16', ]

house/views.py
from django.shortcuts import render, redirect
from .models import *
from .forms import *
from django.contrib.auth.decorators import login_required


def home(request):
    houses = House.objects.all()
    return render(request, 'home.html', {'houses': houses})


@login_required(login_url='/auth/login/')
def create(request):
    form = BaseForm(request.POST, request.FILES)
    image_form = ImageForm(request.POST, request.FILES)
    if request.method == 'POST':
        if form.is_valid():
            dom = House.objects.create(user=request.user, **form.cleaned_data)
            if image_form.is_valid():
                a = image_form.save(commit=False)
                a.house = dom
                a.save()
        if dom.type == 'квартира':
            return redirect('house:create_apartment', dom.pk)
        if dom.type == 'дом':
            return redirect('house:create_house', dom.pk)
    return render(request, 'create.html', {'form': form, 'form2': image_form})


def create_apartment(request, pk):
    house = House.objects.get(pk=pk)
    form = ApartamentForm(request.POST, instance=house)
    if request.method == 'POST' and form.is_valid():
        form.save()
        return redirect('house:home')
    return render(request, 'create_apartament.html', {'form': form})


def create_house(request, pk):
    house = House.objects.get(pk=pk)
    form = HouseForm(request.POST, instance=house)
    if request.method == 'POST' and form.is_valid():
        form.save()
        return redirect('house:home')
    return render(request, 'create_house.html', {'form': form})


def detail(request, pk):
    house = House.objects.get(pk=pk)
    images = Image.objects.filter(house=house)
    return render(request, 'detail.html', {'house': house, 'images': images})

house/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
        {% endblock %}
    </title>
    <link rel="stylesheet" href="{% static 'main.css' %}">
    <link rel='icon' href='{% static '25694.png' %}' type='image/x-icon'>
</head>
<body>
<nav class="navbar background-light-sea">
    <a href="{% url 'house:home' %}" class="nav-item">Главная</a>
    <a href="{% url 'house:create' %}" class="nav-item">Добавить объявление</a>
    {% if user.is_authenticated %}
        <a href="{% url 'auth:logout' %}" class="nav-item">Выход</a>
        <a href="{% url 'auth:profile' %}" class="nav-item"><img height="50" width="50"
                                                                 style="border-radius: 50%; border: 1px solid grey"
                                                                 src="{{ user.profile.avatar.url }}" alt=""></a>
    {% else %}
        <a href="{% url 'auth:register' %}" class="nav-item">Зарегистрироваться</a>
        <a href="{% url 'auth:login' %}" class="nav-item">Войти</a>
    {% endif %}
</nav>
<div class="columns">
    <div class="add"></div>
    <div style="width: 60%;">
        {% block content %}
        {% endblock %}
        {% block script %}
        {% endblock %}
    </div>
    <div class="add"></div>
</div>
<script src="{% static 'carousel.js' %}"></script>
<script src="{% static 'select.js' %}"></script>
</body>
</html>

house/templates/create.html
{% extends 'base.html' %}
{% block content %}
        <form class="form" method="post" enctype="multipart/form-data" action="">
            {% csrf_token %}
            {% for field in form %}
                <div class="field">
                    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                {{ field }}
                </div>
            {% endfor %}
            <button class="button" type="submit">Дальше</button>
        </form>
{% endblock %}

house/templates/create_apartament.html
{% extends 'base.html' %}
{% block content %}
        <form class="form" method="post" enctype="multipart/form-data" action="">
            {% csrf_token %}
            {% for field in form %}
                <div class="field">
                    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                {{ field }}
                </div>
            {% endfor %}
            <button class="button" type="submit">Дальше</button>
        </form>
{% endblock %}

house/templates/create_house.html
{% extends 'base.html' %}
{% block content %}
        <form class="form" method="post" enctype="multipart/form-data" action="">
            {% csrf_token %}
            {% for field in form %}
                <div class="field">
                    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                {{ field }}
                </div>
            {% endfor %}
            <button class="button" type="submit">Дальше</button>
        </form>
{% endblock %}

house/templates/detail.html
{% extends 'base.html' %}
{% block title %}
    {{ house.title }}
{% endblock %}
{% block content %}
    <div class="section">
        <h1 class="title is-1 text-centered">{{ house.title }}</h1>
        <div class="slideshow-container">
            {% for image in images %}
                <div class="mySlides fade">
                    <img class="imgs" src="{{ image.image1.url }}" alt="">
                </div>
                <div class="mySlides fade">
                    <img class="imgs" src="{{ image.image2.url }}" alt="">
                </div>
                <div class="mySlides fade">
                    <img class="imgs" src="{{ image.image3.url }}" alt="">
                </div>
                <div class="mySlides fade">
                    <img class="imgs" src="{{ image.image4.url }}" alt="">
                </div>
                <div class="mySlides fade">
                    <img class="imgs" src="{{ image.image5.url }}" alt="">
                </div>
                <div class="mySlides fade">
                    <img class="imgs" src="{{ image.image5.url }}" alt="">
                </div>
                <div class="mySlides fade">
                    <img class="imgs" src="{{ image.image6.url }}" alt="">
                </div>
                <div class="mySlides fade">
                    <img class="imgs" src="{{ image.image7.url }}" alt="">
                </div>
                <div class="mySlides fade">
                    <img class="imgs" src="{{ image.image8.url }}" alt="">
                </div>
                <div class="mySlides fade">
                    <img class="imgs" src="{{ image.image9.url }}" alt="">
                </div>
                <div class="mySlides fade">
                    <img class="imgs" src="{{ image.image10.url }}" alt="">
                </div>
                <div class="mySlides fade">
                    <img class="imgs" src="{{ image.image11.url }}" alt="">
                </div>
                <div class="mySlides fade">
                    <img class="imgs" src="{{ image.image12.url }}" alt="">
                </div>
                <div class="mySlides fade">
                    <img class="imgs" src="{{ image.image13.url }}" alt="">
                </div>
                <div class="mySlides fade">
                    <img class="imgs" src="{{ image.image14.url }}" alt="">
                </div>
                <div class="mySlides fade">
                    <img class="imgs" src="{{ image.image15.url }}" alt="">
                </div>
                <div class="mySlides fade">
                    <img class="imgs" src="{{ image.image16.url }}" alt="">
                </div>
            {% endfor %}
            <a class="prev" onclick="plusSlides(-1)">&#10094;</a>
            <a class="next" onclick="plusSlides(1)">&#10095;</a>
        </div>
        <div class="about">
            <div class="border">
                Тип жилья: {{ house.type }}
            </div>
            <div class="border">
                Цена: {{ house.price }}
            </div>
            <div class="border">
                Размер дома: {{ house.size }}
            </div>
            <div class="border">
                Материал: {{ house.material }}
            </div>
            <div class="border">
                Количество комнат: {{ house.rooms }}
            </div>
            <div class="border">
                Мебилизация: {{ house.furniture }}
            </div>
            <div class="border">
                Ремонт: {{ house.repair }}
            </div>
            <div class="border">
                Дата постройки: {{ house.date_of_building }}
            </div>
            <div class="border">
                Поблизости: {{ house.near }}
            </div>

            {% if house.type == 'квартира' %}
                <div class="border">
                    Этаж: {{ house.floor }}
                </div>
                <div class="border">
                    Этажность дома: {{ house.storeys }}
                </div>
                <div class="border">
                    Тип строения: {{ house.building_type }}
                </div>
            {% endif %}
            {% if house.type == 'дом' %}
                <div class="border">
                    Жилая площадь: {{ house.living_space }}
                </div>
                <div class="border">
                    Местонахождение: {{ house.location }}
                </div>
                <div class="border">
                    Удобства: {{ house.convenience }}
                </div>
            {% endif %}
        </div>
        <div class="title is-1">Описание</div>
        <br>
        <div class="desk">
            {{ house.bio }}
        </div>
    </div>
{% endblock %}

house/templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Главная
{% endblock %}
{% block content %}
    <div class="section">
        <div class="columns">
            {% for house in houses %}
                <div class="card">
                    <a href="{% url 'house:detail' house.pk %}">
                        <div class="image">
                            <img width="100%" height="100%" src="{{ house.preview.url }}" alt="">
                        </div>
                        <div class="title is-fixed is-3 text-centered">
                            {{ house.home_title }}...
                        </div>
                        <div class="title is-4">
                            {{ house.price }} sum
                        </div>
                        <div class="title is-6">
                            На сайте с: {{ house.date_added }}
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}